### ISSUE TITLE
论坛的通知如何实现的呢？

### ISSUE THREAD

**Issue by hellokaton** [zh-h/spring-abc#1]
![_20160427105523](https://cloud.githubusercontent.com/assets/3849072/14840419/babf85be-0c66-11e6-9d43-ba225f01bfe1.png)

这里不知道你的思路是怎样的，请教一下

**Comment by zh-h** [comment]
直接查询的啊[https://github.com/zh-h/spring-abc/blob/master/src/main/java/xyz/springabc/web/front/NotificationC.java](https://github.com/zh-h/spring-abc/blob/master/src/main/java/xyz/springabc/web/front/NotificationC.java)，前端 Javascript定时访问该路径，有新通知就显示出来。

**Comment by hellokaton** [comment]
soga😂
