### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by fqdeng** [zh-h/spring-abc#2]
我在Idea里面全部设置为UTF8 tomcat也是utf-8 web.xml也配置了springmvc拦截器为utf8能改的地方都改了

还是乱码 无语

**Comment by zh-h** [comment]
是數據庫出現亂碼嗎？請確定數據庫編碼是否正確，創建數據庫的時候指定編碼`CREATE DATABASE IF NOT EXISTS springabc DEFAULT CHARACTER SET utf8;`

**Comment by fqdeng** [comment]
不是哦，是jsp页面的中文全都乱码了，其余的好好的 我也没弄懂什么原因，编码问题一直都 很头疼，一般都是开始项目就全部UTF8

**Comment by zh-h** [comment]
等我下班再折騰

**Comment by zh-h** [comment]
用发布版本没问题 [https://github.com/zh-h/spring-abc/releases](https://github.com/zh-h/spring-abc/releases) 我都忘了我在主干做了什么鬼

**Comment by fqdeng** [comment]
解压替换了源代码果断好了....

**Comment by fqdeng** [comment]
作为一个初学者 再提一个傻逼的问题， nav.jsp 里面 貌似有${p.nav_main.content}  这个application 变量是在哪里定义的？

**Comment by zh-h** [comment]
在 header.jsp 里

**Comment by zh-h** [comment]
不要用主干代码。。。
